---
# metrics are deployed using openshift_hosted_metrics_deploy=true since 3.3
- name: Copy the metrics service account definition
  copy: src="metrics-service-account.yaml" dest="."
  tags: hawkular-metrics

- name: Create service account for metrics deployer
  action: command oc create -n openshift-infra -f metrics-service-account.yaml
  tags: hawkular-metrics

- name: Grant edit permission on project openshift-infra for the service account metric-deployer
  action: command oadm policy add-role-to-user \
          edit system:serviceaccount:openshift-infra:metrics-deployer -n openshift-infra
  tags: hawkular-metrics

- name: Grant Heapster service account the cluster-reader permission to read the stats
  action: command oadm policy add-cluster-role-to-user \
          cluster-reader system:serviceaccount:openshift-infra:heapster -n openshift-infra
  tags: hawkular-metrics

- name: Grant Hawkular service account the view permission view resource in openshift-infra
  action: command oc adm policy add-role-to-user view system:serviceaccount:openshift-infra:hawkular -n openshift-infra
  tags: hawkular-metrics

- name: Create a "dummy" secret that does not specify a certificate value for the metrics deployer
  action: command oc secrets new metrics-deployer nothing=/dev/null -n openshift-infra
  tags: hawkular-metrics

# Should replace this copy by a copy from /usr/share/openshift/examples/infrastructure-templates/enterprise/metrics-deployer.yaml
- name: Copy the metric deployer template
  copy: src="metrics-deployer.yaml" dest="."
  tags: hawkular-metrics

- name: Process the metrics deployer
  shell: command oc process -f  metrics-deployer.yaml -v \
          HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.example.com -v USE_PERSISTENT_STORAGE=false  | oc create -n openshift-infra -f -
  tags: hawkular-metrics
#
# in
# vi /etc/origin/master/master-config.yaml
# add
# assetConfig:
#   logoutURL: ""
#   masterPublicURL: https://ose-master.example.com:8443
#   publicURL: https://ose-master.example.com:8443/console/
#   metricsPublicURL: https://hawkular-metrics.example.com/hawkular/metrics
#

- name: Add metrics URL in master config
  lineinfile: "dest=/etc/origin/master/master-config.yaml state=present insertafter='  publicURL: https://ose-master.example.com:8443/console/' line='  metricsPublicURL: https://hawkular-metrics.example.com/hawkular/metrics'"
  tags: hawkular-metrics
