---

- name: Master to be schedulable
  action: command oadm manage-node ose-master.example.com --schedulable=true

- name: Create registry on master
  action: command oadm registry --config=/etc/origin/master/admin.kubeconfig \
            --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' \
            --selector='region=primary,zone=master'
  ignore_errors: yes
