---

- name: Install NFS Client utils
  yum: name=nfs-utils state=latest
  tags: nfs-client

- name: Install NFS Client rcp-bind
  yum: name=rpcbind state=latest
  tags: nfs-client


- name: Enable NFS Client
  service: name=rpcbind state=started enabled=yes
  tags: nfs-client

# setsebool -P virt_sandbox_use_nfs 1
- name: Confiture SELinux NFS Client
  action: command setsebool -P virt_sandbox_use_nfs 1
  tags: nfs-client


# setsebool -P virt_use_nfs 1
- name: Confiture SELinux NFS Client
  action: command setsebool -P virt_use_nfs 1
  tags: nfs-client

