
#https://bugzilla.redhat.com/show_bug.cgi?id=1481366
#due to VirtualBox enp0s3 on ip address 10.0.2.15
- name: Correction 3.6 related to dnsmasd.d remove when patched
  copy: src="origin-dns.conf.j2" dest="/usr/share/ansible/openshift-ansible/roles/openshift_node_dnsmasq/templates/"
  tags: patchinstaller

- name: Correction 3.6 related to dnsmasd.d behaviour on Vagrant
  copy: src="origin-upstream-dns.conf" dest="/etc/dnsmasq.d"
  tags: patchinstaller

- name: Correction 3.6 related to dnsmasd.d behaviour on Vagrant
  action: command chattr +i /etc/dnsmasq.d/origin-upstream-dns.conf
  tags: patchinstaller

#- name: Correction to 3.7 installer as described here https://github.com/openshift/openshift-ansible/pull/6211/files remove when patched
# patch applied on the 18 th of dec
#  copy: src="glusterblock_deploy.yml" dest="/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/"
#  tags: patchinstaller

#- name: Correction to 3.7 installer as described here https://github.com/openshift/openshift-ansible/pull/6211/files remove when patched
# patch applied on the 18 th of dec
#  action: command chattr +i /usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/glusterblock_deploy.yml
#  tags: patchinstaller
