---

- hosts: infra
  user: root
  roles:
  - gitlab
  - nexus

- hosts: nodes
  user: root

  roles:
  - nfsclient


- hosts: master
  user: root

  roles:
  - registry
  - router
  - persistentvolumes
  - metrics
  - examples
  - jenkins

