---

- hosts: utils
  user: root
  roles:
  - gitlab
  - nexus

- hosts: nodes
  user: root
  roles:
  - nfsclient


- hosts: master
  user: root
  roles:
  - persistentvolumes
# registry and router are now created by installer on node region=infra (3.2.1.9-1-g2265530)
#  - registry
#  - router
  - metrics
  - examples
  - jenkins

