---
#- include: playbooks/reboot_new_hosts.yml

- hosts: new-servers
  user: root

  roles:
    - network
    - subscriptions
    - docker

- hosts: dns-servers
  user: root

  roles:
    - dnsmasq

- hosts: nfs-servers
  user: root

  roles:
    - nfsserver

- hosts: gluster-servers
  user: root

  roles:
    - glusterstorage

#https://bugzilla.redhat.com/show_bug.cgi?id=1481366
#due to VirtualBox enp0s3 on ip address 10.0.2.15
- hosts: master
  user: root

  roles:
    - patchinstaller

