---
#- include: playbooks/reboot_new_hosts.yml

- hosts: new-servers
  user: root

  roles:
    - network
    - subscriptions
    - docker

- hosts: dns-servers
  user: root

  roles:
    - dnsmasq

- hosts: nfs-servers
  user: root

  roles:
    - nfsserver

- hosts: gluster-servers
  user: root

  roles:
    - glusterstorage

- host: master
  user: root

  roles:
    - patchinstaller

