---
- name: Create files for GitLab
  file: path={{ item }} state=directory
  with_items:
    - /srv/gitlab
    - /srv/gitlab/data
    - /srv/gitlab/config
    - /srv/gitlab/logs
  tags: gitlab

- name: Start Git Lab
  action: command sudo docker run --detach \
          --hostname gitlab.example.com \
          --publish 443:443 --publish 80:80 --publish 8022:22 \
          --name gitlab \
          --restart always \
          --volume /srv/gitlab/config:/etc/gitlab:Z \
          --volume /srv/gitlab/logs:/var/log/gitlab:Z \
          --volume /srv/gitlab/data:/var/opt/gitlab:Z \
          gitlab/gitlab-ce:latest
  tags: gitlab
  ignore_errors: yes

- name: Wait for Git Lab to start
  wait_for: host=gitlab.example.com port=80 delay=60
  tags: gitlab

- name: Copy script update gitlab password
  copy: src="gitlabpwd.sh" dest="." mode="0755"
  tags: gitlab

- name: Change Git Lab root password
  shell: ./gitlabpwd.sh
  tags: gitlab
#
#
# SE Linux : Z options avaiable only in Ansible 2.1, OSE Ansible version is 1.9.4
#
#- name: Add adequate EPEL repos
#  action: command wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#
#- name: Add adequate EPEL repos
#  action: command rpm -Uvh epel-release-latest-7*.rpm
#  ignore_errors: yes
#
#- name: Workaround for Ansible issue adding epel
#  yum: name=epel-release state=latest
#
#- name: Workaround for Ansible issue adding docker python
#  yum: name=docker-python state=latest
#
#- name: Workaround for Ansible issue - make sure pip is installed
#  yum: name=python-pip state=latest
#
#- name: Workaround for Ansible issue - make sure required PyPi packages are installed
#  pip: name={{ item }} state=present
#  with_items:
#    - docker-py==1.2.3
#    - six>=1.4.0
#
# SE Linux : Z options avaiable only in Ansible 2.1, OSE Ansible version is 1.9.4
#
#- name: Start Git Lab docker container
#  docker:
#    name: gitlab
#    image: gitlab/gitlab-ce:latest
#    hostname: gitlab.example.com
#    ports:
#      - 443:443
#      - 80:80
#      - 8022:22
#    restart_policy: always
#    volumes:
#      - /srv/gitlab/config:/etc/gitlab:Z
#      - /srv/gitlab/logs:/var/log/gitlab:Z
#      - /srv/gitlab/data:/var/opt/gitlab:Z
#  tags: gitlab
